import Head from 'next/head'
import Banner from "../components/banner/Banner"
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import LargeCard from "../components/LargeCard/LargeCard";
import MediumCard from "../components/MediumCard/MediumCard";
import SmallCard from "../components/SmallCard/SmallCard";


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Airbnb - Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
        <main  className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
        <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
        </section>
        </main>
    </div>
  )
}


export async function getStaticProps() {
  const exploreData = await fetch("https://links.papareact.com/pyp").then(
    (res) => res.json()
  );

  const cardsData = await fetch("https://links.papareact.com/zp1").then((res) =>
    res.json()
  );

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}