import Head from 'next/head'
import Banner from "../components/banner/Banner"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Airbnb - Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}
